//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademiPlus_Transportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransportation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTransportation()
        {
            this.TblProcess = new HashSet<TblProcess>();
        }
    
        public int TransportationID { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Employee { get; set; }
        public string Status { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProcess> TblProcess { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
